// Classic issuer setup for one programme: flags, thresholds, signers, and the
// threshold classification that makes the approval signer unable to mint or claw back.
import {
  Account,
  Asset,
  AuthClawbackEnabledFlag,
  AuthRequiredFlag,
  AuthRevocableFlag,
  BASE_FEE,
  Operation,
  Transaction,
  TransactionBuilder,
  type xdr,
} from '@stellar/stellar-sdk';
import type { Programme, Rules } from '../config.js';

export type Threshold = 'low' | 'med' | 'high';

/**
 * Threshold category per operation, from the Stellar docs "List of operations"
 * (developers.stellar.org/docs/learn/fundamentals/transactions/list-of-operations).
 * SetOptions is high only when it changes signers, weights or thresholds, which is
 * the only way this project uses it after setup.
 */
export const OP_THRESHOLD: Record<string, Threshold> = {
  setTrustLineFlags: 'low',
  allowTrust: 'low',
  bumpSequence: 'low',
  payment: 'med',
  clawback: 'med',
  changeTrust: 'med',
  createAccount: 'med',
  pathPaymentStrictSend: 'med',
  pathPaymentStrictReceive: 'med',
  manageData: 'med',
  setOptions: 'high',
  accountMerge: 'high',
};

export interface IssuerPolicy {
  thresholds: { low: number; med: number; high: number };
  masterWeight: number;
  opsKeyWeight: number;
  approvalSignerWeight: number;
}

export function policyFrom(p: Programme): IssuerPolicy {
  const i = p.file.issuer;
  return { thresholds: i.thresholds, masterWeight: i.master_weight, opsKeyWeight: i.ops_key_weight, approvalSignerWeight: i.approval_signer_weight };
}

/** Can a single signer of `weight` authorise `opType` on the issuer under `policy`? */
export function canAuthorise(policy: IssuerPolicy, weight: number, opType: string): boolean {
  const t = OP_THRESHOLD[opType];
  if (!t) throw new Error(`no threshold classification for ${opType}`);
  return weight >= policy.thresholds[t];
}

export const ISSUER_FLAGS = AuthRequiredFlag | AuthRevocableFlag | AuthClawbackEnabledFlag;

export interface IssuerSetup {
  issuer: string;
  opsKey: string;
  approvalSigner: string;
  homeDomain: string;
  policy: IssuerPolicy;
}

/**
 * SetOptions operations, in order: flags + home domain, the two extra signers, then
 * master weight and thresholds last (the transaction is authorised under the account's
 * pre-transaction thresholds, so the master key alone can submit it).
 */
export function issuerSetupOps(s: IssuerSetup): xdr.Operation[] {
  return [
    Operation.setOptions({ setFlags: ISSUER_FLAGS as never, homeDomain: s.homeDomain }),
    Operation.setOptions({ signer: { ed25519PublicKey: s.opsKey, weight: s.policy.opsKeyWeight } }),
    Operation.setOptions({ signer: { ed25519PublicKey: s.approvalSigner, weight: s.policy.approvalSignerWeight } }),
    Operation.setOptions({
      masterWeight: s.policy.masterWeight,
      lowThreshold: s.policy.thresholds.low,
      medThreshold: s.policy.thresholds.med,
      highThreshold: s.policy.thresholds.high,
    }),
  ];
}

export function buildIssuerSetupTx(issuerAccount: Account, s: IssuerSetup, networkPassphrase: string): Transaction {
  const b = new TransactionBuilder(issuerAccount, { fee: BASE_FEE, networkPassphrase });
  for (const op of issuerSetupOps(s)) b.addOperation(op);
  return b.setTimeout(300).build();
}

export function voucherAssets(rules: Rules, issuer: string): Asset[] {
  return [...rules.assets.keys()].map((code) => new Asset(code, issuer));
}

/** SEP-1 [[CURRENCIES]] entries for the regulated voucher assets. */
export function stellarToml(p: Programme, rules: Rules, issuer: string): string {
  const lines: string[] = [
    `# stellar.toml for ${p.file.home_domain} (programme ${p.id})`,
    '# Generated by `voucher issue`. The approval_criteria hash is sha256(rules.json).',
    'VERSION = "2.7.0"',
    `NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"`,
    `ACCOUNTS = ["${issuer}"]`,
    '',
  ];
  for (const [code, a] of rules.assets) {
    const criteria = `${rules.file.summary} Rules version ${rules.file.version}, sha256(rules.json) = ${rules.hash}.`;
    lines.push(
      '[[CURRENCIES]]',
      `code = "${code}"`,
      `issuer = "${issuer}"`,
      'display_decimals = 2',
      `name = "${a.category === 'food' ? 'Food voucher' : 'Farm-input voucher'} (${p.id})"`,
      `desc = "Restricted-use ${a.category} voucher. 1 unit = 1 USD of entitlement, redeemable by registered merchants at par for USDC."`,
      'is_asset_anchored = false',
      'status = "test"',
      'regulated = true',
      `approval_server = "${p.file.approval_server}"`,
      `approval_criteria = "${criteria.replace(/"/g, '\\"')}"`,
      '',
    );
  }
  return lines.join('\n');
}

/** stellar-cli commands to deploy one SAC per asset and hand its admin to the pool. */
export function sacCommands(rules: Rules, issuer: string, network = 'testnet'): string[] {
  const out: string[] = [];
  for (const code of rules.assets.keys()) {
    out.push(`stellar contract asset deploy --asset ${code}:${issuer} --source agency-master --network ${network}`);
    out.push(
      `stellar contract invoke --id $(stellar contract id asset --asset ${code}:${issuer} --network ${network}) --source agency-master --network ${network} -- set_admin --new_admin <redeem_pool for ${code}>`,
    );
  }
  return out;
}
